--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2
-- Dumped by pg_dump version 12.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: address; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.address (
    id integer NOT NULL,
    facility_name character varying(50),
    contact_name character varying(50),
    mobile_number character varying(20),
    email character varying(20),
    address_line_one character varying(50),
    barangay character varying(50),
    city character varying(50) NOT NULL,
    province character varying(50) NOT NULL,
    landmark character varying(50)
);


ALTER TABLE public.address OWNER TO flag;

--
-- Name: address_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: currencies; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.currencies (
    id integer NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(50)
);


ALTER TABLE public.currencies OWNER TO flag;

--
-- Name: currencies_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.currencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: current_dispatch_status; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.current_dispatch_status (
    id integer NOT NULL,
    inbound_id integer NOT NULL,
    status_id integer NOT NULL,
    date timestamp without time zone
);


ALTER TABLE public.current_dispatch_status OWNER TO flag;

--
-- Name: current_dispatch_status_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.current_dispatch_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.current_dispatch_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: current_pickup_status; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.current_pickup_status (
    id integer NOT NULL,
    inbound_id integer NOT NULL,
    status_id integer NOT NULL,
    date timestamp without time zone
);


ALTER TABLE public.current_pickup_status OWNER TO flag;

--
-- Name: current_pickup_status_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.current_pickup_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.current_pickup_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO flag;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO flag;

--
-- Name: dispatch_statuses; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.dispatch_statuses (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(50)
);


ALTER TABLE public.dispatch_statuses OWNER TO flag;

--
-- Name: dispatch_statuses_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.dispatch_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dispatch_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: donation_requests; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.donation_requests (
    id integer NOT NULL,
    donor_id integer NOT NULL,
    request_type_id integer NOT NULL,
    request_status_id integer NOT NULL,
    currency_id integer NOT NULL,
    estimatedvalue double precision,
    createdate timestamp without time zone,
    lastmodified timestamp without time zone
);


ALTER TABLE public.donation_requests OWNER TO flag;

--
-- Name: donation_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.donation_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.donation_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: donor_address; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.donor_address (
    id integer NOT NULL,
    donor_id integer NOT NULL,
    address_id integer NOT NULL
);


ALTER TABLE public.donor_address OWNER TO flag;

--
-- Name: donor_address_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.donor_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.donor_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: donor_statuses; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.donor_statuses (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    description character varying(50)
);


ALTER TABLE public.donor_statuses OWNER TO flag;

--
-- Name: donor_statuses_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.donor_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.donor_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: donor_types; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.donor_types (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    description character varying(50)
);


ALTER TABLE public.donor_types OWNER TO flag;

--
-- Name: donor_types_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.donor_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.donor_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: donors; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.donors (
    id integer NOT NULL,
    affiliation_org character varying(50),
    representative_name character varying(50),
    mobile_number character varying(20),
    donor_type_id integer NOT NULL,
    sector_type_id integer NOT NULL,
    email character varying(50)
);


ALTER TABLE public.donors OWNER TO flag;

--
-- Name: donors_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.donors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.donors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fleets; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.fleets (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    fleet_contact character varying(50),
    fleet_leader character varying(50),
    description character varying(50)
);


ALTER TABLE public.fleets OWNER TO flag;

--
-- Name: fleets_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.fleets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fleets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inbound_dispatches; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.inbound_dispatches (
    id integer NOT NULL,
    pickup_location_id integer NOT NULL,
    package_id integer NOT NULL,
    fleet_id integer NOT NULL,
    request_remark character varying(50),
    photo_reference character varying(50),
    pickup_timestamp timestamp without time zone
);


ALTER TABLE public.inbound_dispatches OWNER TO flag;

--
-- Name: inbound_dispatches_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.inbound_dispatches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inbound_dispatches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_categories; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.item_categories (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    description character varying(50)
);


ALTER TABLE public.item_categories OWNER TO flag;

--
-- Name: item_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.item_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: otp_requests; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.otp_requests (
    id integer NOT NULL,
    mobile_number character varying(20),
    transaction_type character varying(20),
    reference_code character varying(20),
    validation_code character varying(20),
    expiry timestamp without time zone
);


ALTER TABLE public.otp_requests OWNER TO flag;

--
-- Name: otp_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.otp_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: outbound_dispatches; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.outbound_dispatches (
    id integer NOT NULL,
    destination_id integer NOT NULL,
    package_id integer NOT NULL,
    fleet_id integer NOT NULL,
    unit_id integer NOT NULL,
    total_unit_value double precision NOT NULL,
    photo_reference character varying(50),
    delivery_remark character varying(50),
    pickup_timestamp timestamp without time zone
);


ALTER TABLE public.outbound_dispatches OWNER TO flag;

--
-- Name: outbound_dispatches_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.outbound_dispatches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbound_dispatches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: package_contents; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.package_contents (
    id integer NOT NULL,
    item_category_id integer NOT NULL,
    weight double precision,
    unit_id integer NOT NULL,
    total_unit_value double precision NOT NULL,
    remaining_unit_value double precision,
    currency_id integer NOT NULL,
    monetary_value double precision,
    category_remarks character varying(50)
);


ALTER TABLE public.package_contents OWNER TO flag;

--
-- Name: package_contents_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.package_contents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.package_contents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: packages; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.packages (
    id integer NOT NULL,
    donor_request_id integer NOT NULL,
    package_remarks text,
    currency_id integer NOT NULL,
    totalweight double precision,
    value double precision
);


ALTER TABLE public.packages OWNER TO flag;

--
-- Name: packages_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.packages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.packages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pickup_schedules; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.pickup_schedules (
    id integer NOT NULL,
    dispatch_request_id integer NOT NULL,
    schedule_start timestamp without time zone,
    schedule_end timestamp without time zone
);


ALTER TABLE public.pickup_schedules OWNER TO flag;

--
-- Name: pickup_schedules_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.pickup_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pickup_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pickup_statuses; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.pickup_statuses (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(50)
);


ALTER TABLE public.pickup_statuses OWNER TO flag;

--
-- Name: pickup_statuses_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.pickup_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pickup_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: request_statuses; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.request_statuses (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    description character varying(50)
);


ALTER TABLE public.request_statuses OWNER TO flag;

--
-- Name: request_statuses_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.request_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: request_types; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.request_types (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    description character varying(50)
);


ALTER TABLE public.request_types OWNER TO flag;

--
-- Name: request_types_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.request_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requestor_statuses; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.requestor_statuses (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    description character varying(50)
);


ALTER TABLE public.requestor_statuses OWNER TO flag;

--
-- Name: requestor_statuses_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.requestor_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requestor_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requestor_types; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.requestor_types (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    description character varying(50)
);


ALTER TABLE public.requestor_types OWNER TO flag;

--
-- Name: requestor_types_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.requestor_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requestor_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requestors; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.requestors (
    id integer NOT NULL,
    first_name character varying(50),
    last_name character varying(50),
    mobile_number character varying(50),
    requestor_type_id integer NOT NULL,
    "group" character varying(50),
    email character varying(50),
    requestor_status_id integer NOT NULL
);


ALTER TABLE public.requestors OWNER TO flag;

--
-- Name: requestors_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.requestors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requestors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sector_types; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.sector_types (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    description character varying(50)
);


ALTER TABLE public.sector_types OWNER TO flag;

--
-- Name: sector_types_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.sector_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sector_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: units; Type: TABLE; Schema: public; Owner: flag
--

CREATE TABLE public.units (
    id integer NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(20)
);


ALTER TABLE public.units OWNER TO flag;

--
-- Name: units_id_seq; Type: SEQUENCE; Schema: public; Owner: flag
--

ALTER TABLE public.units ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.units_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: address; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.address (id, facility_name, contact_name, mobile_number, email, address_line_one, barangay, city, province, landmark) FROM stdin;
\.


--
-- Data for Name: currencies; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.currencies (id, code, name) FROM stdin;
1       USD     United States Dollars
2       PHP     Philippine Peso
\.


--
-- Data for Name: current_dispatch_status; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.current_dispatch_status (id, inbound_id, status_id, date) FROM stdin;
\.


--
-- Data for Name: current_pickup_status; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.current_pickup_status (id, inbound_id, status_id, date) FROM stdin;
\.


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
create-requestor-types-table    dexter  db/changelog-1.0.xml    2020-05-06 18:06:27.726549      1       EXECUTED       8:f78e4950f4b11a4ad08c3bae75e5a173       createTable tableName=requestor_types           \N      3.8.7   \N      \N     8788387500
load-initial-requestor-types    dexter  db/changelog-1.0.xml    2020-05-06 18:06:28.154079      2       EXECUTED       8:15d6465e4168bd1d493f3ec0abcb9b4a       loadData tableName=requestor_types              \N      3.8.7   \N      \N     8788387500
create-requestor-statuses-table dexter  db/changelog-1.0.xml    2020-05-06 18:06:28.336638      3       EXECUTED       8:cf0e5bb19c44e6cb53d5ff3ad44b0abc       createTable tableName=requestor_statuses                \N      3.8.7   \N     \N       8788387500
load-initial-requestor-statuses dexter  db/changelog-1.0.xml    2020-05-06 18:06:28.917112      4       EXECUTED       8:4d312fd33138637ab25184cb74363272       loadData tableName=requestor_statuses           \N      3.8.7   \N      \N     8788387500
create-requestors-table dexter  db/changelog-1.0.xml    2020-05-06 18:06:29.14968       5       EXECUTED        8:920df21efc585a7fe9d3fe5a3d5ef7f8      createTable tableName=requestors                \N      3.8.7   \N      \N      8788387500
create-sector-types-table       nitz    db/changelog-1.0.xml    2020-05-06 18:06:29.351627      6       EXECUTED       8:90cc1755669217cd55c2e172e480ae52       createTable tableName=sector_types              \N      3.8.7   \N      \N     8788387500
load-initial-sector-types       dexter  db/changelog-1.0.xml    2020-05-06 18:06:30.026862      7       EXECUTED       8:b6a7d0538b580c80f37d673e4fa15491       loadData tableName=sector_types         \N      3.8.7   \N      \N      8788387500
create-donor-types-table        dexter  db/changelog-1.0.xml    2020-05-06 18:06:30.351077      8       EXECUTED       8:da45890817f8623339a4e174129f7cdf       createTable tableName=donor_types               \N      3.8.7   \N      \N     8788387500
load-initial-donor-types        dexter  db/changelog-1.0.xml    2020-05-06 18:06:30.979831      9       EXECUTED       8:0e3d13762a45cb8c847c6c45a6ff2c6e       loadData tableName=donor_types          \N      3.8.7   \N      \N      8788387500
create-donor-statuses-table     dexter  db/changelog-1.0.xml    2020-05-06 18:06:31.166107      10      EXECUTED       8:400850b62ea8124ed537959a0342cae3       createTable tableName=donor_statuses            \N      3.8.7   \N      \N     8788387500
load-initial-donor-statuses     dexter  db/changelog-1.0.xml    2020-05-06 18:06:31.884705      11      EXECUTED       8:547011e3c2536bb0ccf3302f49797157       loadData tableName=donor_statuses               \N      3.8.7   \N      \N     8788387500
create-donors-table     dexter  db/changelog-1.0.xml    2020-05-06 18:06:32.023976      12      EXECUTED        8:1b95c06dd0d715f975fe33b62f21cee1      createTable tableName=donors            \N      3.8.7   \N      \N      8788387500
create-request-types-table      dexter  db/changelog-1.0.xml    2020-05-06 18:06:32.178916      13      EXECUTED       8:c0c585864d070c19a5ed3ea1dce30b49       createTable tableName=request_types             \N      3.8.7   \N      \N     8788387500
load-initial-request-types      dexter  db/changelog-1.0.xml    2020-05-06 18:06:33.040598      14      EXECUTED       8:ce42e0176e24bd098ccd3d80206dca02       loadData tableName=request_types                \N      3.8.7   \N      \N     8788387500
create-request-statuses-table   nitz    db/changelog-1.0.xml    2020-05-06 18:06:33.239107      15      EXECUTED       8:1e76baae852482d845bf1ae678b07c57       createTable tableName=request_statuses          \N      3.8.7   \N      \N     8788387500
load-initial-request-statuses   nitz    db/changelog-1.0.xml    2020-05-06 18:06:34.35735       16      EXECUTED       8:e7f6f5e06349989c660348f4f9ca2ef6       loadData tableName=request_statuses             \N      3.8.7   \N      \N     8788387500
create-currencies-table nitz    db/changelog-1.0.xml    2020-05-06 18:06:34.54033       17      EXECUTED        8:c1f013676f4ee20be1f7cd99bb2eebfc      createTable tableName=currencies                \N      3.8.7   \N      \N      8788387500
load-initial-currencies nitz    db/changelog-1.0.xml    2020-05-06 18:06:35.350405      18      EXECUTED        8:27f5fdcd9f089c6a448404c76bcc17af      loadData tableName=currencies           \N      3.8.7   \N      \N      8788387500
create-donation-requests-table  dexter  db/changelog-1.0.xml    2020-05-06 18:06:35.460665      19      EXECUTED       8:a39e32424bc87503d9fce7baf08f6ed2       createTable tableName=donation_requests         \N      3.8.7   \N      \N     8788387500
create-packages-table   dexter  db/changelog-1.0.xml    2020-05-06 18:06:35.631607      20      EXECUTED        8:33b2dfe2e9197ec30fa9c14521d82c60      createTable tableName=packages          \N      3.8.7   \N      \N      8788387500
create-item-categories-table    dexter  db/changelog-1.0.xml    2020-05-06 18:06:35.757414      21      EXECUTED       8:92c467220fd1fc6e8389d7851e6da3f6       createTable tableName=item_categories           \N      3.8.7   \N      \N     8788387500
load-initial-item-categories    dexter  db/changelog-1.0.xml    2020-05-06 18:06:36.803985      22      EXECUTED       8:b51e5dc1019c298d53bd5d7b35f0d450       loadData tableName=item_categories              \N      3.8.7   \N      \N     8788387500
create-item-units-table dexter  db/changelog-1.0.xml    2020-05-06 18:06:36.927634      23      EXECUTED        8:56993b10c5991af1af6bddc3538afd61      createTable tableName=units             \N      3.8.7   \N      \N      8788387500
load-initial-units      dexter  db/changelog-1.0.xml    2020-05-06 18:06:38.13231       24      EXECUTED        8:245f68f04bcd9c2cb270b15d2066d40e      loadData tableName=units                \N      3.8.7   \N      \N      8788387500
create-package-contents-table   dexter  db/changelog-1.0.xml    2020-05-06 18:06:38.252417      25      EXECUTED       8:f9c870cdf32cea660c3326d098601f76       createTable tableName=package_contents          \N      3.8.7   \N      \N     8788387500
create-dispatch-statuses-table  nitz    db/changelog-1.0.xml    2020-05-06 18:06:38.461641      26      EXECUTED       8:f823a3581e0a0512fdd59e47c51b8fa0       createTable tableName=dispatch_statuses         \N      3.8.7   \N      \N     8788387500
load-initial-dispatch-statuses  nitz    db/changelog-1.0.xml    2020-05-06 18:06:40.024327      27      EXECUTED       8:47a318666c057b21110f9cd87aeec6e4       loadData tableName=dispatch_statuses            \N      3.8.7   \N      \N     8788387500
create-pickup-statuses-table    nitz    db/changelog-1.0.xml    2020-05-06 18:06:40.20758       28      EXECUTED       8:5a1bc9c994e5f513255ae864448a8b6d       createTable tableName=pickup_statuses           \N      3.8.7   \N      \N     8788387500
load-initial-pickup-statuses    nitz    db/changelog-1.0.xml    2020-05-06 18:06:41.900261      29      EXECUTED       8:96105951fb1cce947d8d84413a95466d       loadData tableName=pickup_statuses              \N      3.8.7   \N      \N     8788387500
create-fleets-table     nitz    db/changelog-1.0.xml    2020-05-06 18:06:42.10175       30      EXECUTED        8:12b28fc65624a3a29c22e9084c8a03d6      createTable tableName=fleets            \N      3.8.7   \N      \N      8788387500
create-address-table    nitz    db/changelog-1.0.xml    2020-05-06 18:06:42.259203      31      EXECUTED        8:e218c199d08c31cdf9adf1523ac228ea      createTable tableName=address           \N      3.8.7   \N      \N      8788387500
create-donor-address-table      nitz    db/changelog-1.0.xml    2020-05-06 18:06:42.43655       32      EXECUTED       8:e458e020904b5c32c58edc752fcaf4c2       createTable tableName=donor_address             \N      3.8.7   \N      \N     8788387500
create-inbound-dispatches-table nitz    db/changelog-1.0.xml    2020-05-06 18:06:42.60111       33      EXECUTED       8:b51fbab68af8da0cc8c82b11151480ee       createTable tableName=inbound_dispatches                \N      3.8.7   \N     \N       8788387500
create-current-pickup-status-table      nitz    db/changelog-1.0.xml    2020-05-06 18:06:42.788294      34      EXECUTED8:6addb773a81a1ffda938bf7d2e950809      createTable tableName=current_pickup_status             \N      3.8.7   \N     \N       8788387500
create-outbound-dispatches-table        nitz    db/changelog-1.0.xml    2020-05-06 18:06:42.995703      35      EXECUTED8:7015ab13dea463b7b43c50da06ba1f20      createTable tableName=outbound_dispatches               \N      3.8.7   \N     \N       8788387500
create-current-dispatch-status-table    nitz    db/changelog-1.0.xml    2020-05-06 18:06:43.149535      36      EXECUTED8:1dc1107305ebd93f42f7e4e374ad311d      createTable tableName=current_dispatch_status           \N      3.8.7   \N     \N       8788387500
create-pickup-schedules-table   dexter  db/changelog-1.0.xml    2020-05-06 18:06:43.319175      37      EXECUTED       8:d5f28ddb471d153aa37e01caa9ff0df9       createTable tableName=pickup_schedules          \N      3.8.7   \N      \N     8788387500
create-otp-requests-table       dexter  db/changelog-1.0.xml    2020-05-06 18:06:43.490933      38      EXECUTED       8:e97d41e549db613557e4c67fcae0f9f7       createTable tableName=otp_requests              \N      3.8.7   \N      \N     8788387500
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1       f       \N      \N
\.


--
-- Data for Name: dispatch_statuses; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.dispatch_statuses (id, name, description) FROM stdin;
1       Preparing for Delivery  Preparing package for delivery
2       Ready for Delivery      Preparing package for delivery
3       Delivery In Transit     Fleet carrying the package is in transit
4       Delivery Completed      Package delivered
5       Delivery Failed Failed to delivery package
\.


--
-- Data for Name: donation_requests; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.donation_requests (id, donor_id, request_type_id, request_status_id, currency_id, estimatedvalue, createdate, lastmodified) FROM stdin;
\.


--
-- Data for Name: donor_address; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.donor_address (id, donor_id, address_id) FROM stdin;
\.


--
-- Data for Name: donor_statuses; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.donor_statuses (id, name, description) FROM stdin;
1       Guest   Guest has no login credentials
2       Pending Pending verification
3       Active  Verified and active
4       Inactive        Deactivated
\.


--
-- Data for Name: donor_types; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.donor_types (id, name, description) FROM stdin;
1       Individual      Covers private individuals
2       Organization    Covers different organizations
\.


--
-- Data for Name: donors; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.donors (id, affiliation_org, representative_name, mobile_number, donor_type_id, sector_type_id, email) FROM stdin;
\.


--
-- Data for Name: fleets; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.fleets (id, name, fleet_contact, fleet_leader, description) FROM stdin;
\.


--
-- Data for Name: inbound_dispatches; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.inbound_dispatches (id, pickup_location_id, package_id, fleet_id, request_remark, photo_reference, pickup_timestamp) FROM stdin;
\.


--
-- Data for Name: item_categories; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.item_categories (id, name, description) FROM stdin;
1       FOOD_1  Food (Non-Perishable)
2       FOOD_2  Food (Perishable)
3       WATER   Water
4       TEST_KITS       Test Kits
5       PPE_SUIT        Protective Bodysuites
6       PPE_MASKS       Masks
7       PPE_SHOE_COVER  Shoe Covers
8       PPE_GLOVES      Gloves
9       PPE_FACE_SHIELDS        Face Shields
10      CLOTHES Clothes
11      VITAMINS        Vitamins
12      ALCOHOL Alcohol
13      MEDICINE        Medicine
14      THERMOMETER     Thermometer
15      MED_SUPPLIES    Medical Supplies
\.


--
-- Data for Name: otp_requests; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.otp_requests (id, mobile_number, transaction_type, reference_code, validation_code, expiry) FROM stdin;
\.


--
-- Data for Name: outbound_dispatches; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.outbound_dispatches (id, destination_id, package_id, fleet_id, unit_id, total_unit_value, photo_reference, delivery_remark, pickup_timestamp) FROM stdin;
\.


--
-- Data for Name: package_contents; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.package_contents (id, item_category_id, weight, unit_id, total_unit_value, remaining_unit_value, currency_id, monetary_value, category_remarks) FROM stdin;
\.


--
-- Data for Name: packages; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.packages (id, donor_request_id, package_remarks, currency_id, totalweight, value) FROM stdin;
\.


--
-- Data for Name: pickup_schedules; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.pickup_schedules (id, dispatch_request_id, schedule_start, schedule_end) FROM stdin;
\.


--
-- Data for Name: pickup_statuses; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.pickup_statuses (id, name, description) FROM stdin;
1       Preparing Package       Preparing package for pickup
2       Ready for Pickup        Package ready for pickup
3       Pickup Fleet In Transit Fleet assigned to pickup the package is in transit
4       Pickup Completed        Package picked up
5       Pickup Failed   Failed to pick up package
\.


--
-- Data for Name: request_statuses; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.request_statuses (id, name, description) FROM stdin;
1       Approved        Donation request approved
2       Rejected        Donation request rejected
3       Pending Donation request pending
\.


--
-- Data for Name: request_types; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.request_types (id, name, description) FROM stdin;
1       For Pickup      I am requestion OCD to pick it up
2       For Reporting   I have made a donation but would like to report it
3       For OCD Dropoff I prefer to to deliver it at OCD site
\.


--
-- Data for Name: requestor_statuses; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.requestor_statuses (id, name, description) FROM stdin;
1       GUEST   Guest has no login credentials
2       PENDING Pending verification
3       ACTIVE  Verified and active
4       INACTIVE        Deactivated
\.


--
-- Data for Name: requestor_types; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.requestor_types (id, name, description) FROM stdin;
1       Individual      Covers private individuals
2       Organization    Covers different organizations
\.


--
-- Data for Name: requestors; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.requestors (id, first_name, last_name, mobile_number, requestor_type_id, "group", email, requestor_status_id) FROM stdin;
\.


--
-- Data for Name: sector_types; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.sector_types (id, name, description) FROM stdin;
1       Private Individual or Organization
2       Government      This covers government
3       CivilSociety    Non-goverment organization
\.


--
-- Data for Name: units; Type: TABLE DATA; Schema: public; Owner: flag
--

COPY public.units (id, code, name) FROM stdin;
1       BX      Boxes
2       GL      Galoons
3       PCS     Pieces
4       PRS     Pairs
\.


--
-- Name: address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.address_id_seq', 1, false);


--
-- Name: currencies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.currencies_id_seq', 2, true);


--
-- Name: current_dispatch_status_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.current_dispatch_status_id_seq', 1, false);


--
-- Name: current_pickup_status_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.current_pickup_status_id_seq', 1, false);


--
-- Name: dispatch_statuses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.dispatch_statuses_id_seq', 5, true);


--
-- Name: donation_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.donation_requests_id_seq', 1, false);


--
-- Name: donor_address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.donor_address_id_seq', 1, false);


--
-- Name: donor_statuses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.donor_statuses_id_seq', 4, true);


--
-- Name: donor_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.donor_types_id_seq', 2, true);


--
-- Name: donors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.donors_id_seq', 1, false);


--
-- Name: fleets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.fleets_id_seq', 1, false);


--
-- Name: inbound_dispatches_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.inbound_dispatches_id_seq', 1, false);


--
-- Name: item_categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.item_categories_id_seq', 15, true);


--
-- Name: otp_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.otp_requests_id_seq', 1, false);


--
-- Name: outbound_dispatches_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.outbound_dispatches_id_seq', 1, false);


--
-- Name: package_contents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.package_contents_id_seq', 1, false);


--
-- Name: packages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.packages_id_seq', 1, false);


--
-- Name: pickup_schedules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.pickup_schedules_id_seq', 1, false);


--
-- Name: pickup_statuses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.pickup_statuses_id_seq', 5, true);


--
-- Name: request_statuses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.request_statuses_id_seq', 3, true);


--
-- Name: request_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.request_types_id_seq', 3, true);


--
-- Name: requestor_statuses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.requestor_statuses_id_seq', 4, true);


--
-- Name: requestor_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.requestor_types_id_seq', 2, true);


--
-- Name: requestors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.requestors_id_seq', 1, false);


--
-- Name: sector_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.sector_types_id_seq', 3, true);


--
-- Name: units_id_seq; Type: SEQUENCE SET; Schema: public; Owner: flag
--

SELECT pg_catalog.setval('public.units_id_seq', 4, true);


--
-- Name: address address_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (id);


--
-- Name: currencies currencies_code_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_code_key UNIQUE (code);


--
-- Name: currencies currencies_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_pkey PRIMARY KEY (id);


--
-- Name: current_dispatch_status current_dispatch_status_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.current_dispatch_status
    ADD CONSTRAINT current_dispatch_status_pkey PRIMARY KEY (id);


--
-- Name: current_pickup_status current_pickup_status_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.current_pickup_status
    ADD CONSTRAINT current_pickup_status_pkey PRIMARY KEY (id);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: dispatch_statuses dispatch_statuses_name_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.dispatch_statuses
    ADD CONSTRAINT dispatch_statuses_name_key UNIQUE (name);


--
-- Name: dispatch_statuses dispatch_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.dispatch_statuses
    ADD CONSTRAINT dispatch_statuses_pkey PRIMARY KEY (id);


--
-- Name: donation_requests donation_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donation_requests
    ADD CONSTRAINT donation_requests_pkey PRIMARY KEY (id);


--
-- Name: donor_address donor_address_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donor_address
    ADD CONSTRAINT donor_address_pkey PRIMARY KEY (id);


--
-- Name: donor_statuses donor_statuses_name_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donor_statuses
    ADD CONSTRAINT donor_statuses_name_key UNIQUE (name);


--
-- Name: donor_statuses donor_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donor_statuses
    ADD CONSTRAINT donor_statuses_pkey PRIMARY KEY (id);


--
-- Name: donor_types donor_types_name_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donor_types
    ADD CONSTRAINT donor_types_name_key UNIQUE (name);


--
-- Name: donor_types donor_types_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donor_types
    ADD CONSTRAINT donor_types_pkey PRIMARY KEY (id);


--
-- Name: donors donors_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donors
    ADD CONSTRAINT donors_pkey PRIMARY KEY (id);


--
-- Name: fleets fleets_name_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.fleets
    ADD CONSTRAINT fleets_name_key UNIQUE (name);


--
-- Name: fleets fleets_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.fleets
    ADD CONSTRAINT fleets_pkey PRIMARY KEY (id);


--
-- Name: inbound_dispatches inbound_dispatches_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.inbound_dispatches
    ADD CONSTRAINT inbound_dispatches_pkey PRIMARY KEY (id);


--
-- Name: item_categories item_categories_name_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.item_categories
    ADD CONSTRAINT item_categories_name_key UNIQUE (name);


--
-- Name: item_categories item_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.item_categories
    ADD CONSTRAINT item_categories_pkey PRIMARY KEY (id);


--
-- Name: otp_requests otp_requests_mobile_number_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.otp_requests
    ADD CONSTRAINT otp_requests_mobile_number_key UNIQUE (mobile_number);


--
-- Name: otp_requests otp_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.otp_requests
    ADD CONSTRAINT otp_requests_pkey PRIMARY KEY (id);


--
-- Name: outbound_dispatches outbound_dispatches_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.outbound_dispatches
    ADD CONSTRAINT outbound_dispatches_pkey PRIMARY KEY (id);


--
-- Name: package_contents package_contents_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.package_contents
    ADD CONSTRAINT package_contents_pkey PRIMARY KEY (id);


--
-- Name: packages packages_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.packages
    ADD CONSTRAINT packages_pkey PRIMARY KEY (id);


--
-- Name: pickup_schedules pickup_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.pickup_schedules
    ADD CONSTRAINT pickup_schedules_pkey PRIMARY KEY (id);


--
-- Name: pickup_statuses pickup_statuses_name_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.pickup_statuses
    ADD CONSTRAINT pickup_statuses_name_key UNIQUE (name);


--
-- Name: pickup_statuses pickup_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.pickup_statuses
    ADD CONSTRAINT pickup_statuses_pkey PRIMARY KEY (id);


--
-- Name: request_statuses request_statuses_name_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.request_statuses
    ADD CONSTRAINT request_statuses_name_key UNIQUE (name);


--
-- Name: request_statuses request_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.request_statuses
    ADD CONSTRAINT request_statuses_pkey PRIMARY KEY (id);


--
-- Name: request_types request_types_name_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.request_types
    ADD CONSTRAINT request_types_name_key UNIQUE (name);


--
-- Name: request_types request_types_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.request_types
    ADD CONSTRAINT request_types_pkey PRIMARY KEY (id);


--
-- Name: requestor_statuses requestor_statuses_name_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.requestor_statuses
    ADD CONSTRAINT requestor_statuses_name_key UNIQUE (name);


--
-- Name: requestor_statuses requestor_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.requestor_statuses
    ADD CONSTRAINT requestor_statuses_pkey PRIMARY KEY (id);


--
-- Name: requestor_types requestor_types_name_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.requestor_types
    ADD CONSTRAINT requestor_types_name_key UNIQUE (name);


--
-- Name: requestor_types requestor_types_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.requestor_types
    ADD CONSTRAINT requestor_types_pkey PRIMARY KEY (id);


--
-- Name: requestors requestors_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.requestors
    ADD CONSTRAINT requestors_pkey PRIMARY KEY (id);


--
-- Name: sector_types sector_types_name_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.sector_types
    ADD CONSTRAINT sector_types_name_key UNIQUE (name);


--
-- Name: sector_types sector_types_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.sector_types
    ADD CONSTRAINT sector_types_pkey PRIMARY KEY (id);


--
-- Name: units units_code_key; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_code_key UNIQUE (code);


--
-- Name: units units_pkey; Type: CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_pkey PRIMARY KEY (id);


--
-- Name: current_dispatch_status fk_current_dispatch_status; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.current_dispatch_status
    ADD CONSTRAINT fk_current_dispatch_status FOREIGN KEY (status_id) REFERENCES public.dispatch_statuses(id);


--
-- Name: current_dispatch_status fk_current_dispatch_status_inbound; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.current_dispatch_status
    ADD CONSTRAINT fk_current_dispatch_status_inbound FOREIGN KEY (inbound_id) REFERENCES public.outbound_dispatches(id);


--
-- Name: current_pickup_status fk_current_pickup_status; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.current_pickup_status
    ADD CONSTRAINT fk_current_pickup_status FOREIGN KEY (status_id) REFERENCES public.pickup_statuses(id);


--
-- Name: current_pickup_status fk_current_pickup_status_inbound; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.current_pickup_status
    ADD CONSTRAINT fk_current_pickup_status_inbound FOREIGN KEY (inbound_id) REFERENCES public.inbound_dispatches(id);


--
-- Name: donation_requests fk_donation_currency; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donation_requests
    ADD CONSTRAINT fk_donation_currency FOREIGN KEY (currency_id) REFERENCES public.currencies(id);


--
-- Name: donation_requests fk_donation_request_status; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donation_requests
    ADD CONSTRAINT fk_donation_request_status FOREIGN KEY (request_status_id) REFERENCES public.request_statuses(id);


--
-- Name: donation_requests fk_donation_requests_request_type; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donation_requests
    ADD CONSTRAINT fk_donation_requests_request_type FOREIGN KEY (request_type_id) REFERENCES public.request_types(id);


--
-- Name: donor_address fk_donor_address; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donor_address
    ADD CONSTRAINT fk_donor_address FOREIGN KEY (address_id) REFERENCES public.address(id);


--
-- Name: donors fk_donor_sector; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donors
    ADD CONSTRAINT fk_donor_sector FOREIGN KEY (sector_type_id) REFERENCES public.sector_types(id);


--
-- Name: donors fk_donor_type; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donors
    ADD CONSTRAINT fk_donor_type FOREIGN KEY (donor_type_id) REFERENCES public.donor_types(id);


--
-- Name: donation_requests fk_donotion_requests_donor; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donation_requests
    ADD CONSTRAINT fk_donotion_requests_donor FOREIGN KEY (donor_id) REFERENCES public.donors(id);


--
-- Name: inbound_dispatches fk_inbound_fleet; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.inbound_dispatches
    ADD CONSTRAINT fk_inbound_fleet FOREIGN KEY (fleet_id) REFERENCES public.fleets(id);


--
-- Name: inbound_dispatches fk_inbound_package; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.inbound_dispatches
    ADD CONSTRAINT fk_inbound_package FOREIGN KEY (package_id) REFERENCES public.packages(id);


--
-- Name: inbound_dispatches fk_inbound_pickup_location; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.inbound_dispatches
    ADD CONSTRAINT fk_inbound_pickup_location FOREIGN KEY (pickup_location_id) REFERENCES public.address(id);


--
-- Name: outbound_dispatches fk_outbound_destination; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.outbound_dispatches
    ADD CONSTRAINT fk_outbound_destination FOREIGN KEY (destination_id) REFERENCES public.address(id);


--
-- Name: outbound_dispatches fk_outbound_dispatch_unit; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.outbound_dispatches
    ADD CONSTRAINT fk_outbound_dispatch_unit FOREIGN KEY (unit_id) REFERENCES public.units(id);


--
-- Name: outbound_dispatches fk_outbound_fleet; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.outbound_dispatches
    ADD CONSTRAINT fk_outbound_fleet FOREIGN KEY (fleet_id) REFERENCES public.fleets(id);


--
-- Name: outbound_dispatches fk_outbound_package; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.outbound_dispatches
    ADD CONSTRAINT fk_outbound_package FOREIGN KEY (package_id) REFERENCES public.packages(id);


--
-- Name: package_contents fk_package_content_currency; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.package_contents
    ADD CONSTRAINT fk_package_content_currency FOREIGN KEY (currency_id) REFERENCES public.currencies(id);


--
-- Name: package_contents fk_package_content_item_category; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.package_contents
    ADD CONSTRAINT fk_package_content_item_category FOREIGN KEY (item_category_id) REFERENCES public.item_categories(id);


--
-- Name: package_contents fk_package_content_unit; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.package_contents
    ADD CONSTRAINT fk_package_content_unit FOREIGN KEY (unit_id) REFERENCES public.units(id);


--
-- Name: packages fk_package_currency; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.packages
    ADD CONSTRAINT fk_package_currency FOREIGN KEY (currency_id) REFERENCES public.currencies(id);


--
-- Name: packages fk_package_donation_request; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.packages
    ADD CONSTRAINT fk_package_donation_request FOREIGN KEY (donor_request_id) REFERENCES public.donation_requests(id);


--
-- Name: donor_address fk_pickup_location_donor; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.donor_address
    ADD CONSTRAINT fk_pickup_location_donor FOREIGN KEY (donor_id) REFERENCES public.donors(id);


--
-- Name: pickup_schedules fk_pickup_schedules_dispatch_request_id; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.pickup_schedules
    ADD CONSTRAINT fk_pickup_schedules_dispatch_request_id FOREIGN KEY (dispatch_request_id) REFERENCES public.inbound_dispatches(id);


--
-- Name: requestors fk_requestor_status; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.requestors
    ADD CONSTRAINT fk_requestor_status FOREIGN KEY (requestor_status_id) REFERENCES public.requestor_statuses(id);


--
-- Name: requestors fk_requestor_type; Type: FK CONSTRAINT; Schema: public; Owner: flag
--

ALTER TABLE ONLY public.requestors
    ADD CONSTRAINT fk_requestor_type FOREIGN KEY (requestor_type_id) REFERENCES public.requestor_types(id);


--
-- PostgreSQL database dump complete
--

