version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./docker-files/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:9.0.2
    restart: always
    depends_on:
      - postgres
    env_file: .env
    ports:
      - 8180:8080
  minio:
    image: minio/minio:RELEASE.2020-04-10T03-34-42Z
    volumes:
      - /data
      # - ./docker-files/minio/data:/data
    ports:
      - 9000:9000
    env_file: .env
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
